#!/bin/bash

set -e
echo "
=================
  Quality check
=================
"

echo "=== golangci-lint ===\n"
golangci-lint run --enable-all

echo "=== go vet ===\n"
go vet ./...

echo "=== go fmt ===\n"
go fmt ./...

echo "=== git add ===\n"
git add .
